Develop
Svetlana-Seregina/java-filmorate pull request #14
Opened 2022-11-25 21:59 UTC by Svetlana-Seregina

2022-11-27 14:21 UTC, krylov-sergey-sergeevich requested changes
Привет
1) Я достаточно редко проверяю групповой проект(их мало), поэтому если что напоминайте какие нибудь тонкости и первый вопрос, это нормально разве что задача на проверку была отправлена от Дмитрия, а репозиторий Светланы?

2) Я не могу в гитхабе комментировать то что было до этого, но мне немного не нравится pom.xml, зачем там кое где лишние версии (или не лишние и есть логика?)

3) Следующий пункт логи, вот вы выбрали алгоритмы которые хотите реализовать, я как ревьювер могу искать и проверять что все есть, но в реальном мире все алгоритмы имеют название/номер чаще и то и то, например у меня на работе дают названия на подобии TS-1 TS-2 TS-3 в документации соответственно есть эти же номера, а далее в коде в логах мы пишем "TS-1 создание того того" и если у кого-то есть вопрос по реализации он идет в документацию и ищет по номеру алгоритма. Итого: Просьба в реадми или в описание PR пронумеровать алгоритмы и добавить в логах соответствующие номера.

4) Запросы красивые, но в них легко запутаться поэтому по возможности давайте вынесем повторяющиеся логические цепочки чтобы не дублировать и по пути как раз еще раз проверим логику

В целом вы молодцы, давайте доработаем эту задаче и будет совсем хорошо =)
В случае вопросов я доступен в слаке и в пачке(тут реже).

2022-11-27 14:21 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
Прошу подумать и возможно где-то размеры для строк расставить более кхм соответствующе

2022-11-27 14:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/LikeService.java
> +        log.info(String.valueOf(popularFilms));
А там лог прям красивый будет?)

2022-11-27 14:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/LikeService.java
> +            throw new EntityNotFoundException("Нет лайков у фильма " + filmId);
У фильма нет лайков, или у фильма + этого человека нет лайка? Ошибка должна быть очень точной и не вводить в заблуждение

2022-11-27 14:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +@Slf4j
Аннотация есть, а логов нет, где-то грустит один котик

2022-11-27 14:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DirectorDaoImpl.java
> +        jdbcTemplate.batchUpdate("INSERT INTO film_directors (FILM_ID, DIRECTOR_ID) VALUES (?, ?)", args);
Почему batchUpdate  использован?

Это не критика, интересно почему так решили

2022-11-27 14:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/FilmDaoImpl.java
> +        String sqlQuery;
Нельзи ли тут попытаться как то общую часть вынести запроса?

2022-11-27 14:21 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/ReviewDaoImpl.java
> +public class ReviewDaoImpl implements ReviewDao {
Подумать нет ли в запросах общих частей которые потом будет тяжело поддерживать

2022-11-28 12:55 UTC, Scutc commented on README.md
> +
Расширили readme

2022-11-28 13:28 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
Добавили везде печать в лог и текст ошибки информацию по пути, по которому произошла проблема. Реализовали через HttpServletRequest

2022-11-28 13:35 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public boolean RemoveLikeToReview(@PathVariable long reviewId, @PathVariable long userId) {
поправил

2022-11-28 13:35 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public boolean RemoveDislikeToReview(@PathVariable long reviewId, @PathVariable long userId) {
Поправил

2022-11-28 19:29 UTC, Svetlana-Seregina commented on src/main/resources/schema.sql
размеры строк исправлены

2022-11-28 20:16 UTC, Svetlana-Seregina commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DirectorDaoImpl.java
> +        jdbcTemplate.batchUpdate("INSERT INTO film_directors (FILM_ID, DIRECTOR_ID) VALUES (?, ?)", args);
Использован batchUpdate, чтобы собранные в один пакет запросы отправить одним разом.

2022-11-28 22:58 UTC, jacksonDenisov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +public class ReviewController {
сделано

2022-11-28 22:59 UTC, jacksonDenisov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.debug("Обрабатываем запрос на создание фильма " + film);
привели к единому стилю

2022-11-28 23:03 UTC, jacksonDenisov commented on src/main/java/ru/yandex/practicum/filmorate/service/LikeService.java
> +            throw new EntityNotFoundException("Нет лайков у фильма " + filmId);
поправили

2022-11-28 23:03 UTC, jacksonDenisov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +@Slf4j
тоже поправили

2022-11-29 08:39 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/service/LikeService.java
> +        log.info(String.valueOf(popularFilms));
Логи исправили везде, теперь все красиво =)

2022-11-29 08:41 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/FilmDaoImpl.java
> +        String sqlQuery;
Большинство сложных запросов декомпозировали на набор констант

2022-11-29 08:41 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/ReviewDaoImpl.java
> +public class ReviewDaoImpl implements ReviewDao {
Подумали и вынесли общие части запросов в константы

2022-11-29 08:49 UTC, Scutc commented
Привет, спасибо за ревью!
Обработали все твои комментарии и отписались в деталях. Дополнительно докинули интеграционных тестов. 
По общим вопросам:
1) Да, это нормально, что репозиторий не тимлида. Нам и Глеб (наставник) и Саша(куратор) подтвердили, что это ОК =) Репозиторий Светланы выбрали на общекомандном голосовании после ознакомления с проектами друг друга
2) POM.xml поправили, лишние версии убрали
3) Пронумеровали весь функционал в README и в логах пишем ссылки на номера требований
4) Запросы к базе декомпозировали. Среди нас нет единого мнения о том, что так стало лучше. Кажется, что восприятие логики работы с базой в таком случае ухудшается. При этом поддерживать такой код будет конечно проще, т.к. не нужно менять одни и те же блоки в разных местах приложения - достаточно обновить только константы

Надеемся на финальную приемку нашей работы :)

2022-11-29 20:15 UTC, krylov-sergey-sergeevich approved these changes
Привет, отличная работа, надеюсь в командной работе вам понравилось развивать проект. В большинстве случаев вы морально должны быть готовы что 1 + 1 разработчик это не 2 реализованных фичи, а дай бог 1.5, к сожалению это реальность. И чем лучше в команде процессы, жесткое руководство(но адекватное) оформлением кода и реализацией функционала тем выше этот коэф 1.5 -> 2. В особо крутых коллективах иногда происходит синергия и люди дополняют пробелы в знаниях друг друга. Поэтому не бойтесь предлагать какие то общие правила в команде и не надо в штыки воспринимать чужие, надо оценивать + и -.

В общем все хорошо - зачет!

2022-11-29 22:13 UTC, merged